name: Build Android with patched webview 

env:
  QT_VERSION: 6.4.1

on:
  push:
    tags:
      - "qt_android*"
    branches:
      - qt_android

jobs:
  build_qt_android:
    runs-on: ubuntu-latest
    steps:
      - name:                       Checkout code
        id:                         codecheck
        uses:                       actions/checkout@v3

      - name:                       Get git short hash
        id:                         vars
        run:                        echo "sha_short=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name:                       Echo git shorthash
        run:                        echo ${{ steps.vars.outputs.sha_short }}

      - name:                       Build Qt Android
        id:                         qtandroid
        run:                        ./.github/autobuild/qt_android.sh build
        env:
          GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
          QT_VERSION:               ${{ env.QT_VERSION }}
        
      - name:                       Post-Build for Qt Android build
        id:                         get-artifacts
        run:                        ./.github/autobuild/qt_android.sh get-artifacts

      - name:                       Upload Artifact 1 to Job
        uses:                       actions/upload-artifact@v2
        with:
          name:                     ${{ steps.get-artifacts.outputs.artifact_1 }}
          path:                     deploy/${{ steps.get-artifacts.outputs.artifact_1 }}
          retention-days:           31
          if-no-files-found:        error

      - name:                       Create Release
        id:                         create-release
        uses:                       ncipollo/release-action@v1
        with:
          tag:                      androidqt_${{ env.QT_VERSION }}
          artifacts:                "deploy/qt_android_${{ env.QT_VERSION }}.tar.gz"
          draft:                    true
          token:                    ${{ secrets.GITHUB_TOKEN }}
          name:                     Qt_Android_${{ env.QT_VERSION }}
      