name: Build Qt for Mac with IPC Posix shared mem

env:
  QT_VERSION: 6.3.2

on:
  push:
    tags:
      - "qtmac*"
    branches:
      - qtmac

jobs:
  buildqtmac:
    runs-on: macos-12
    steps:
      - name:                       Checkout code
        id:                         codecheck
        uses:                       actions/checkout@v2

      - name:                       Get git short hash
        id:                         vars
        run:                        echo "sha_short=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name:                       Echo git shorthash
        run:                        echo ${{ steps.vars.outputs.sha_short }}

      - name:                       Build Qt for macOS - Posix
        id:                         macqtposix
        run:                        ./.github/autobuild/qt_macos_posix.sh build
        env:
          GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
          QT_VERSION:               ${{ env.QT_VERSION }}
        
      - name:                       Post-Build for macOS QT Posix build
        id:                         get-artifacts
        run:                        ./.github/autobuild/qt_macos_posix.sh get-artifacts

      - name:                       Upload Artifact 1 to Job
        uses:                       actions/upload-artifact@v2
        with:
          name:                     ${{ steps.get-artifacts.outputs.artifact_1 }}
          path:                     deploy/${{ steps.get-artifacts.outputs.artifact_1 }}
          retention-days:           31
          if-no-files-found:        error

      - name:                       Create Release
        id:                         create-release
        uses:                       ncipollo/release-action@v1
        with:
          tag:                      macqt_${{ env.QT_VERSION }}
          artifacts:                "deploy/*.tar.gz"
          draft:                    false
          token:                    ${{ secrets.GITHUB_TOKEN }}
          name:                     Qt_macOS_${{ env.QT_VERSION }}_POSIX
      
